image: openjdk:17-jdk-alpine

stages:
  - test

unit_tests:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    paths:
      - build/reports/tests/test/index.html
    expire_in: 1 week
  only:
    - merge_requests      # Required since "branches" does not cover MRs
    - branches            # Execute on GitPush to this branch
  tags:
    - comp2120